### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by uyot10** [tpaviot/ProcessScheduler#120]
I encountered an error while executing the assignation of required resorces to jobs. The error says the following and it comes from append_z3_assertion function :
`AssertionError: assertion If(Selected_Rec142_297_186664367806730871696048769797360125371,
   And(Rec142_297_maybe_busy_J220_start == J220_start,
       Rec142_297_maybe_busy_J220_end == J220_end),
   And(Rec142_297_maybe_busy_J220_start == -2123,
       Rec142_297_maybe_busy_J220_end == -2123)) already added.`

The error also says to report the issue in this github comment section. I hope someone can help, as i can't find the source of the problem.

**Comment by tpaviot** [comment]
you're trying to add a constraint already added to the solver.  That should not happen, each constraint should be unique. This means there is something wrong with your model. Please insert a code snippet that reproduces the issue if you want a deeper diagnostic
