### ISSUE TITLE
ResourceUnavailable should give same error as WorkLoad when used improperly

### ISSUE THREAD

**Issue by retnuh** [tpaviot/ProcessScheduler#131]
I was struggling to get `ResourceUnavailable` to work properly.  On a whim I tried the `WorkLoad` with a value of 0, as suggested by the docs, and I got the following:

```
The resource is not assigned to any task. WorkLoad constraint meaningless.
```

That made me realize that the contraint needed to be added __after__ the workers was added to the tasks.  After doing that, things worked as expected.

If `ResourceUnavailable` had the same error message that would be helpful for folks new to the library figure out what they are doing wrong.

**Comment by tpaviot** [comment]
Thank you for your feedback. This issue has already been reported and fixed in commit 8cb3ba39ae015620ae3a2dd4ef97fe410a751633 a few weeks ago
