### ISSUE TITLE
DOCS: specify render_gantt_plotly has different parameters in Problem solving/Render to a Gantt chart

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#24]
The last line of this part says: 

> If you prefer plotly, just change the method name to use to render_gantt_plotly().

It would be nice to specify that we can't just change the method name (which, from what I understand, would mean that both methods would have the same parameters and work in the same way), but we also have to change parameters, so we don't have to go into the API documentation to see how this new Plotly method works.

Also, it would be nice to specify that this new method only works for real timepoints problems. (Tried to plot an integer problem with plotly and got no useful plot)

**Comment by tpaviot** [comment]
I have to unify both method signatures so that they take the same attributes. And yes, you're right, plotly only works for real timepoints.

**Comment by tpaviot** [comment]
I have to unify both method signatures so that they take the same attributes. And yes, you're right, plotly only works for real timepoints.

**Comment by dreinon** [comment]
Nice! By the way, very good feedback about plotly! I really like its interface, nice idea implementing it.

**Comment by tpaviot** [comment]
Fix by commit 78b2b2f9f33fcc87689fe544f3adaf31c4fc5a9c

**Comment by tpaviot** [comment]
Doc and real timepoints doc fixed by commit eefa063
