### ISSUE TITLE
Pip version

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#3]
I installed your package using pip, and got the 0.1.0 version. I didn’t notice it wasn’t an updated version until I tried to create a FixedDurationTask with the ‘optional’ keyword parameter set to True, and got an error. After that, I tried to run pip install ... -U to update it, but got as output that I already had the latest version installed, so I finally decided to install the dev version, which is 0.4. I would like to use the latest stable version, which I guess it’s 0.3.0. Could someone please look it up and see if there’s an error in pip?

Thanks :D

**Comment by tpaviot** [comment]
I just checked, and I confirm that the latest package version available from pypi is 0.3.0. In the same time, I tried installing ProcessScheduler from a fresh conda environment et get the following:
```bash
$ pip install ProcessScheduler
Collecting ProcessScheduler
  Downloading ProcessScheduler-0.1.0.tar.gz (34 kB)
Collecting z3-solver
  Using cached z3_solver-4.8.10.0-py2.py3-none-manylinux1_x86_64.whl (32.6 MB)
Building wheels for collected packages: ProcessScheduler
  Building wheel for ProcessScheduler (setup.py) ... done
  Created wheel for ProcessScheduler: filename=ProcessScheduler-0.1.0-py3-none-any.whl size=45814 sha256=4607e25209f4fb3ddd1e3bde51675a1de96123cb389c8cc8e1b2649863e5794d
  Stored in directory: /home/thomas/.cache/pip/wheels/b1/28/93/d51d4280bf6c84e93d342954f1ac33ea87bb20c67e1661a127
Successfully built ProcessScheduler
Installing collected packages: z3-solver, ProcessScheduler
Successfully installed ProcessScheduler-0.1.0 z3-solver-4.8.10.0
```
As the Schrödinger's cat, I agree and disagree at the same time. Let me check what's wrong.

**Comment by dreinon** [comment]
Can I already use pip or should I git clone??
Thanks!

**Comment by tpaviot** [comment]
There was no progress regarding this issue, I did not have time to fix it

**Comment by dreinon** [comment]
No worries!

**Comment by tpaviot** [comment]
I tagged a version ``0.4.0`` and uploaded the package to pypi. It should be fixed, I'll close this ticket when you confirm it is ok

**Comment by dreinon** [comment]
Fixed now! Awesome :)

Thanks!
