### ISSUE TITLE
Cost functions

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/ProcessScheduler#34]
For a ``Task``, the current definition of the ``cost_per_period`` is very poor and does not cover all situations of industrial cases. Indeed, cost functions may depend on time (for example, a cost quadratic function of time). It should be possible to define such functions and run the scheduler/optimizer on top of it.

The z3 solver is able to deal with Real numbers and nonlinear expressions. But none of the exp/sin/cos etc. functions, only polynomials. The best way to go is to define a cost function using only integer numbers. I suggest interpolating any function of one real variable using linear segments defined only with integer numbers. I contributed related code to https://github.com/tpaviot/LinearIntegerInterpolation. It is a very first draft.

ping @dreinon

**Comment by dreinon** [comment]
What about taylor series?

**Comment by tpaviot** [comment]
Taylor series gives you a polynomial approximation around a single point. Here, I rather need an interpolation over a wide range.

**Comment by dreinon** [comment]
True

**Comment by dreinon** [comment]
Do you know spline or kringing iterpolation? Those may give a better function approximation. Although, we may not want a better whole function approximation but rather an easier-to-compute approximation which gives the right results for costs of integers, am I right?

**Comment by tpaviot** [comment]
I don't know the kringing interpolation

**Comment by tpaviot** [comment]
Maybe we can start with implementing a cost function as a linear function on the interval [0, horizon], and see later for interpolating more complex functions, for example:

```python
task1=VariableDurationTask('Task1', cost=CostFunction(cost_task_1 = lambda t : 2*t + 10))
task2=VariableDurationTask('Task1', cost=CostPerPeriod(5))
```
The ``CostFunction`` and ``CostPerPeriod`` would inherit from a ``_Cost`` base class.

What do you think?

**Comment by tpaviot** [comment]
Note:
```
ress2=Worker('Worker2', cost=CostFunction(cost_task_1 = lambda t : 5))
```
This would be equivalent, but less readable

**Comment by dreinon** [comment]
> ```python
> cost_ress_1 
> ```

I don't understand why naming the lambda function, doesn't it work like this:
`ress1=Worker('Worker1', cost=CostFunction(lambda t : 2*t + 10))`
??

**Comment by dreinon** [comment]
Also, what about accepting cost as Union[int, CostFunction]? 
Then, if cost is int, instancing CostPerPeriod(5) inside the function.

This would give a more readable approach, right?

**Comment by tpaviot** [comment]
yes, you're right, no need to name the lambda function

**Comment by dreinon** [comment]
Right. I agree now with that approach.

**Comment by tpaviot** [comment]
Ok, I decided to start simple. I implemented ``ConstantCostPerPeriod`` and what I called ``PolynomialCostFunction``. There are a some related tests

**Comment by tpaviot** [comment]
The first draft is in the master branch. Issue closed, further issues will need another entry.
