### ISSUE TITLE
Warning with Workload constraint

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#48]
I'm adding a workload constraint which dict_time_intervals_and_bound is the following:
```python
{(0, 13): 3, (13, 26): 3, (26, 39): 3, (39, 52): 3, (52, 65): 3, (0, 65): 10}
```
being my horizon 65.

If I add the constraint before assigning tasks to the resource, I get the following warning:
`/home/dani/dribo/trial/ProcessScheduler/processscheduler/base.py:81: UserWarning: assertion True already added.
  warnings.warn('assertion %s already added.' % z3_assertion)`

If I add the constraint after tasks are assigned, it works. Is the constraint intended to work like this?
Thank you!

**Comment by tpaviot** [comment]
I cannot duplicate the issue, can you please provide a simple test case?

**Comment by tpaviot** [comment]
I looked at the related code, you're right: the resource has to be assigned to the tasks before the WorkLoad constraint can be safely added.

**Comment by dreinon** [comment]
Okay, closing the issue and opening one for performance.
