### ISSUE TITLE
Misspelling in API documentation

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#5]
In the Solution section, in the class:
`classprocessscheduler.solution.SchedulingSolution(problem_name)`
Inside the description of the `get_all_tasks_but_unavailable()` method, it says unavailebleResource.

**Comment by tpaviot** [comment]
Thank you for the report, I'll have a deeper look at the documentation.

**Comment by tpaviot** [comment]
Fixed by commit f497ef4f29f39cbc5e491914c5571815ab8af71d
