### ISSUE TITLE
Multi objective optimization performances

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/ProcessScheduler#57]
The built-in optimization solver for z3 appears to be weak regarding scalability. Works well for small problems. Larger problems take too much time to successfully report a solution.

**Comment by tpaviot** [comment]
I have the following idea: turn the multiobjective problem into a single one. If O_i and O_j are two objectives that have to be minimized, then minimize the objective O=W_i*O_i+W_j*O_j where W_i and W_j are integers that represent the objective weights. Solve this single objective using the IncrementalSolver, which has proved to have better performances than the standard optimization solver.

**Comment by tpaviot** [comment]
WIP at dev branch https://github.com/tpaviot/ProcessScheduler/tree/multi-to-single-optimization-objective

**Comment by dreinon** [comment]
This issue is already solved right?

**Comment by tpaviot** [comment]
Yes, I think so. I close the issue. If ever there are new problems with multi-optimization performance, we will open a new ticket.
