### ISSUE TITLE
Possible new design/option for single resource flowtime objective.

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#60]
We found out that what actually counts for us is that the distance between 2 tasks of a resource is 0, and if the distance is anything but 0, then it wouldn't be good for this objective. Therefore, I have thought of a binary variable where the solver gets penalized if distance is not 0 (or maybe rewarded if distance is 0). Also, maybe it could be a parameter of the single resource flowtime objective, for example, if you set parameter force/binary/... to True, the objective adquires this behaviour.

**Comment by dreinon** [comment]
Right, I understand why they have to be sorted. So, you think the implementation would be the same even if we speak about binary (1 if distance is 0, 0 else) instead of just computing pure distance between tasks, right?

**Comment by tpaviot** [comment]
Yes I do. Another possibility would be to add the test ``If(end_task_i==start_task_j, tasks_i_j_contiguous==True, tasks_i_j_contiguous=False)`` for all tasks and all cases. If you have n tasks, this would result in n*(n-1)/2 if/then/else tests. At the end, if you have n True, then all tasks are contiguous. You can force the solver to reach n True in an optimization problem.

**Comment by tpaviot** [comment]
Or another possible expression: if all tasks are contiguous then all start times and end_times are the same, except the start of the first task and the end of the last task.

**Comment by dreinon** [comment]
> Yes I do. Another possibility would be to add the test `If(end_task_i==start_task_j, tasks_i_j_contiguous==True, tasks_i_j_contiguous=False)` for all tasks and all cases. If you have n tasks, this would result in n*(n-1)/2 if/then/else tests. At the end, if you have n True, then all tasks are contiguous. You can force the solver to reach n True in an optimization problem.

Can I make the solver miximize n instead of forcing reaching n?

**Comment by tpaviot** [comment]
No you can't.

**Comment by dreinon** [comment]
Ok.
