### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#65]
Is there any code style in particular being used for this project? I normally use as close as I can PEP style, and I have formatters, linters and precommit hooks to achieve it, but I avoid passing them to files in this project since I don't want to change original style.

**Comment by dreinon** [comment]
Priority: low

**Comment by tpaviot** [comment]
I think I wrote some info into the CONTRIBUTING.md file, but I'm not sure. I only use Codacy for code quality review, but we could automate the execution of a linter as well

**Comment by tpaviot** [comment]
I use to work with PyLint

**Comment by tpaviot** [comment]
We can use Black https://github.com/psf/black No need to discuss any coding style policy

**Comment by tpaviot** [comment]
Just tested it, it's quite comfortable: no need to make any manual change, the code is automatically reformated

**Comment by dreinon** [comment]
Black is nice. The only thing I dislike are double quotes haha, but it's not something super important.

**Comment by tpaviot** [comment]
I suggest we go with black from now. No need to override default values, it's just perfect.

**Comment by dreinon** [comment]
Ok, all good!
