### ISSUE TITLE
Next release 0.7.0

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/ProcessScheduler#72]
There has been quite a lot of work since the last release, I think it's time to release a new version. Todo before the release:

- [ ] Review the documentation. Make sure it is up to date with recent changes
- [ ] Review the README
- [ ] Update version number in setup.py, __init__ and everywhere
- [ ] Review the notebooks that are not part of the documentation
- [ ] Anything else?

**Comment by dreinon** [comment]
Merging unmerged branches.

**Comment by tpaviot** [comment]
Unmerged branches are unsuccessful attempts, they can't be merged as is, but I keep them open because they contain some code that could be useful in the future

**Comment by dreinon** [comment]
What about my contributions to max-utilization branch? I did a PR to that branch instead of to master.

**Comment by tpaviot** [comment]
I can't see any pending pull request, did I miss something?

**Comment by tpaviot** [comment]
You can rebase your changes on top of master and submit a new PR

**Comment by dreinon** [comment]
Hi! What's still left to be done?

**Comment by tpaviot** [comment]
Update documentation. WIP.

**Comment by dreinon** [comment]
May I help w something?

**Comment by tpaviot** [comment]
See https://processscheduler.readthedocs.io/en/latest/, sections First order logics/Indicator and Objective/Solving still need to be reviewed

**Comment by tpaviot** [comment]
dev branch is here: https://github.com/tpaviot/ProcessScheduler/tree/update-doc

**Comment by dreinon** [comment]
Ok, I'll do that!

**Comment by dreinon** [comment]
Don't you think `not_` should accept only one parameter since it's a unary operator? Now it accepts a list and adds the constraint Not(And(list)). I think that if the user want to achieve that, then they should use And(map(not_, list)) for example.

**Comment by tpaviot** [comment]
@dreinon you're right.

**Comment by tpaviot** [comment]
0.7.0 released and uploaded to pypi
