### ISSUE TITLE
[Suggestion] Using Sourcery

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#85]
I suggest looking into [Sourcery](https://sourcery.ai/), a tool that I recently discovered and that works super nice in helping you to write better and cleaner code.

It suggests you refactors to make the code cleaner and more readable, and also rates your methods in the following way:
![image](https://user-images.githubusercontent.com/67071425/127320116-09e29396-afce-4018-888a-a1909c9f6b82.png)

They have plugins for github too.

**Comment by tpaviot** [comment]
ok thank you for the pointer, I didnt' know about this new tool. I will add a github hook, let's see the output

**Comment by tpaviot** [comment]
Here is the sourcerly PR for master branch refactoring

https://github.com/tpaviot/ProcessScheduler/pull/86

interesting indeed

**Comment by dreinon** [comment]
right, very interesting, what's your opinion about it?
IMO, it's worth applying the PR changes since they are automatic, and it is also worth starting using sourcery to make cleaner code, although I would not spend the huge amount of time that refactoring all the current methods would need to increase sourcery score.

**Comment by tpaviot** [comment]
right, we already are using many different tools related to software quality. The processscheduler code is not that bad so far. Running sourcery from time to time as I did, by requesting the refactoring of a branch, is enough IMO.

**Comment by dreinon** [comment]
I agree. Although, it might be interesting starting to use it directly in the editor. I don't know which editor you use but sourcery is available for PyCharm and VSCode, and for Vim and Sublime in BETA.

**Comment by tpaviot** [comment]
SublimeText.

**Comment by dreinon** [comment]
https://github.com/sourcery-ai/sourcery/wiki/Sublime-Usage

**Comment by dreinon** [comment]
Testing the code in my editor, I see black has done an awesome job and that it works pretty nicely :)
Although, there are some small things that still appear in my editor like the following:
![image](https://user-images.githubusercontent.com/67071425/127465149-0f2e918d-7405-4ce0-ab21-ca6a4e566119.png)

It's no big deal but it would be nice to have flake8 checking these things.
I found a github action ready to go [here](https://github.com/marketplace/actions/flake8-action) and a plugin for sublime in case you were interested too [here](https://github.com/SublimeLinter/SublimeLinter-flake8).

Thanks!

**Comment by tpaviot** [comment]
Some of them are false positives. linters are confused by the z3 semantics.
For example, the z3 assertion ``x == False`` is an assignment whereas
python understands it as a comparison. I use the linters just to check
issues I could have missed, the objective is not really to get en empty
report.

**Comment by dreinon** [comment]
Right, I understand!
Should I close this issue?

**Comment by tpaviot** [comment]
Yes, please
